
INSERT INTO `mcq` (`mcq_cat_id`, `mcq`, `op1`, `op2`, `op3`, `op4`, `cop`, `desc`) VALUES
(18, 'The following is not included in title block of drawing sheet', 'sheet no', 'scale', 'method of projection ', 'size of sheet', 'd', ''),
(18, 'Which of the following represent reducing scale?', '1:01', '1:02', '2:01', '10:01', 'b', ''),
(18, 'In first angle projection method, object is assumed to be placed in', 'first quadrant ', 'second quadrant ', 'third quadrant', 'fourth quadrant ', 'a', ''),
(18, 'The following line is used for visible outlines', 'continuous thick ', 'Continuous thin', 'Chain thin line', 'Short zigzag thin', 'a', ''),
(18, 'The following line is used for dimension line', 'continuous thick ', 'Continuous thin', 'Chain thin line', 'Short zigzag thin', 'b', ''),
(18, 'The dotted lines represents', 'Hidden edges', 'Projection line', 'Centre line', 'Hatching line', 'a', ''),
(18, 'Hatching lines are drawn at degree to reference line', '30', '45', '60', '90', 'b', ''),
(18, 'In aligned system of dimensioning, the dimensions may be read from', 'Bottom or right hand edges', 'Bottom or left hand edges', 'Only from bottom', 'Only from left side', 'a', ''),
(18, 'The Length: Width in case of an arrow head is', '1:01', '2:01', '3:01', '4:01', 'c ', ''),
(18, 'The internal angle of regular pentagon is degree', '72', '108', '120', '150', 'a', ''),
(18, 'The internal angle of regular hexagon is degree', '72', '108', '120', '150', 'c', ''),
(18, 'A point ?P? is above Horizontal Plane (HP) and in front of Vertical Plane (VP). The point is in', 'First quadrant', 'Second quadrant', 'Third quadrant', 'Fourth quadrant', 'a', ''),
(18, 'The side view of an object is drawn in', 'Vertical plane', 'Horizontal plane', 'Profile plane', 'Any of the above', 'c', ''),
(18, 'Which type of line is part of a dimension?', 'break lines', 'phantom lines', 'extension lines', 'cutting plane lines', 'c', ''),
(18, 'Which line type is thin and light?', 'visible lines', 'center lines', ' construction lines', 'all of the above', 'c', ''),
(18, 'Which line type is thick and black?', 'visible lines', 'center lines', ' construction lines', 'all of the above', 'a', ''),
(18, 'The top, front, and bottom views align in this manner', 'Horizontally', 'Vertically', 'According to the planar views', 'Parallel to the frontal plane', 'b', ''),
(18, ' If a plane is parallel to the plane of projection, it appears:', 'True size', 'As a line or edge', 'Foreshortened', 'As an oblique surface', 'a', ''),
(18, ' This line pattern is composed of three dashes, one long dash on each end with a short dash in the middle:', 'Object', 'Hidden', 'Center', 'Phantom', 'c', ''),
(18, 'This is the plane upon which the top view is projected:', 'Horizontal', 'Frontal', 'Profile', 'Base', 'a', ''),
(18, 'The primary unit of measurement for engineering drawings and design in the mechanical industries is the:', 'Millimeter', 'Centimeter', 'Meter', 'Kilometer', 'a', ''),
(18, ' Which Type of Line is Thick and Black', 'Visible Line', 'Center Line', ' Construction Line', 'All of above', 'a', ''),
(18, 'which tool can be used to draw a 90 degree line', '30/60 set square', 'protactor', 'drafter', 'All of above', 'd', ''),
(18, ' The Height width and depth of an object can be shown with a minimum of how many orthographic projection views', 'one', 'two', 'six', 'four', 'b', ''),
(18, 'Dimension textis generallyplaced abovethe ________line.', 'Dimension', 'Extension', 'Center', 'Leader', 'a', ''),
(18, 'The line joining the front and top views of a point is called', 'reference line', 'projector ', 'connector', 'locus', 'b', ''),
(18, ' A point lying in the HP, has its top view above XY line. Its front view will be', 'on XY line', 'above XY line', 'below XY line', 'any of these', 'a', ''),
(18, 'A point whose elevation and plan are above XY, is situated in', 'first angle', 'second angle', 'third angle', 'fourth angle', 'b', ''),
(18, 'A point whose elevation is above XY line may be situated in', 'first angle', 'second angle', 'vertical plane', 'any of these', 'd', ''),
(18, 'A point is 20 mm below HP and 30 mm behind VP. Its top view will be', '20 mm below XY', '30 mm below XY', '20 mm above XY', '30 mm above XY', 'd', ''),
(18, 'The front view of a point is 50 mm above xy line and the top view is 20 mm below the front view. the point lies in', 'first angle ', 'second angle', 'third angle ', 'fourth angle', 'b', ''),
(18, 'If both the front and the top views of a pointlie on the opposite side of the reference line the point may be situated in following angles', 'first or second ', 'first or third', 'second or fourth', 'third or fourth', 'b', ''),
(18, 'If both the front and the top views of a point lie on the same side of the reference line the point may be situated in following angles', 'first or second ', 'first or third', 'second or fourth', 'third or fourth', 'c', ''),
(18, 'If top view of a point is situated 60 mm below the reference line and its front view is 20 mm above the top view, the point lies in', 'first angle ', 'second angle', 'third angle', 'fourth angle', 'd', ''),
(18, 'The front view of a point is 40 mm above xy and the top view is 50 mm below xy, the position of point is', '40 mm above HP', '40 mm below HP', '50 mm above HP', '50 mm below HP', 'a', ''),
(18, 'State the position of a point the front view of which lies on the reference line and the top view is 40 mm above it.', '40 mm above HP and in the VP', '40 mm behind VP and in the HP', '40 mm below HP and in the VP', '40 mm in front of VP and in the HP', 'b', ''),
(18, 'State the position of a point the top view of which lies on the reference line and the front view is 30 mm below it.', '30 mm above HP and in the VP', '30 mm behind VP and in the HP', '30 mm below HP and in the VP', '30 mm in front of VP and in the HP', 'a', ''),
(18, 'Projection of an object shown by three views is known as', 'perspective', 'isometric', 'oblique', 'orthographic', 'd', ''),
(18, 'Which of the following describes the theory of orthographic projection?', 'Projectors parallel to each other and perpendicular to the plane of projection', 'Projectors parallel to each other and parallel to the plane of projection', 'Projectors parallel to each other and oblique to the plane of projection', 'Projectors perpendicular to each other and parallel to the plane of projection', 'a', ''),
(18, 'In orthographic projection, the elevation is obtained on a plane called', 'horizontal', 'vertical ', 'profile', 'auxiliary', 'b', ''),
(18, 'In multiview projections, the XY line is also known as', 'Horizontal line', 'Horizontal trace', 'Reference line', 'All of these', 'c', ''),
(18, 'In first angle projection method, the relative positions of the object, plane and observers are', 'Object is placed in between', 'Plane is placed in between', 'Observer is placed in between', 'May be placed in any order', 'a', ''),
(18, 'In first angle projection system, the right hand side view of an object is drawn', 'Above of the elevation', 'Below of the elevation', 'Left of the elevation', 'Right of the elevation', 'c', ''),
(18, 'If the front view of an object exhibits width and height, then what dimensions of an object are exhibited by a right side view?', 'Length and width', 'Length and height', 'Height and width', 'Length and breadth', 'b', ''),
(18, 'For orthographic projections, B.I.S. recommends the following', 'First angle projection', 'Third angle projection', 'Second angle projection', 'Fourth angle projection', 'a', ''),
(18, 'The recommended symbol for indicating the angle of projection shows two views of the frustum of a', 'Square Pyramid', 'Triangular pyramid', 'Cone', 'Any of these', 'c', ''),
(18, 'If a line is parallel to both HP and VP, its true length will be seen in', 'Front View', 'Top View', 'Side view', 'Both front and top views', 'd', ''),
(18, 'If the apparent and the true inclinations of a line with HP are equal, the line is', 'Parallel to horizontal plane', 'Parallel to vertical plane', 'Parallel to profile plane', 'Inclined to both reference planes', 'b', ''),
(18, 'The point at which the line intersects the VP, extended if necessary, is known as', 'Profile trace', 'Horizontal trace', 'Vertical trace', 'Auxiliary trace', 'c', ''),
(18, 'If the front view of a line is parallel to the xy line its true length is shown in', 'Front View', 'Top View', 'Side view', 'Both front and top views', 'b', ''),
(18, 'If top view of a line is a point, its front view is', ' Parallel to xy line and of true length', 'Parallel to xy line and of apparent length', 'Perpendicular to xy line and of true length', 'Perpendicular to xy line and of apparent length', 'c', ''),
(18, 'Horizontal trace of a line exits when the line is', 'Parallel to horizontal plane', 'Inclined to horizontal plane', 'Perpendicular to vertical plane', 'Perpendicular to profile plane', 'b', ''),
(18, 'If a line is inclined at 45? to the HP and 30? to the VP, its front view is inclined at', '30? to xy', ' 45? to xy', 'Between 30? and 45?', 'Greater than 45?', 'd', ''),
(18, 'If a line is inclined at 30? to the HP and 60? to the VP, its front and top views are inclined at an angle of', '30? and 60? to xy respectively', '60? and 30? to xy respectively', 'Both at 90? to xy', 'Both greater than 30? but less than 90?', 'c', ''),
(18, 'For a line situated in the first angle which of the following is not correct', 'HT and VT may lie below xy', 'HT lies below xy and VT lies above xy', 'HT and VT may lie above xy', 'HT lies above xy and VT lies below xy', 'd', ''),
(18, 'A 90 mm long line PQ, inclined at 30? to the HP and 45? to the VP has end P 15 mm above HP and 25 mm in front of VP. The other end Q will lie in', 'First angle', 'Third angle', 'Second or fourth angle', 'Any of these', 'd', ''),
(18, 'If the front and top views of a line are inclined at 30? and 45? to the reference line, the true inclination of the line with HP will be', '30?', '45? ', 'Less than 30?', 'Greater than 45?', 'c', ''),
(18, 'If both the front and top views of a line are perpendicular to the reference line, the true inclination of the line with HP and VP may be respectively', '15? and 75?', '30? and 60?', 'Both 45?', 'Any of these', 'd', ''),
(18, 'A line AB is on the profile plane inclined such that ends of line are 10, 12 cm away from horizontal plane, which view from the following gives the actual length of the line AB?', 'Front view', 'Top view', 'Side view', 'Isometric view', 'c', ''),
(18, 'If a line RS lie on both vertical and horizontal plane then which of the following two views coincides to give a line again?', 'Front, Top', 'Top, Side', 'Side, Isometric', 'Isometric, Front', 'a', ''),
(18, 'A line PQ lie in both the vertical plane and profile plane the front and side views of that line coincides at vertical reference line.', 'TRUE', 'FALSE', '_______', '_______', 'a', ''),
(18, 'If a thin set-square is kept perpendicular to both the horizontal and vertical planes, its true shape is seen in', 'Horizontal plane', 'Vertical plane', 'Auxiliary inclined plane', 'Profile plane', 'd', ''),
(18, 'Planes which are inclined to both the horizontal and vertical planes are called', 'Oblique planes', 'Profile planes', 'Auxiliary planes', 'None of these', 'a', ''),
(18, 'If a thin rectangular plate of 60 mm X 30 mm is inclined at an angle of 60? to HP its top view may be', 'Square of 60 mm side', 'Square of 30 mm side', 'Rectangle of 60 mm X 45 mm', 'Rectangle of 45 mm X 30 mm', 'b', ''),
(18, 'In multi-view orthographic projection, the front view of a circular plane may be', 'A circle', 'An ellipse', 'A straight line', 'Any one of these', 'd', ''),
(18, 'If both front and top views of a plane are straight lines the true shape will lie on', 'Profile plane', 'Horizontal plane', 'Vertical plane', 'Any one of these', 'd', ''),
(18, 'If a circular plane is inclined at 30? with the HP and 60? with the VP its side view will be', 'An ellipse', 'A straight line', 'A circle', 'True shape', 'b', ''),
(18, 'The front view of an elliptical plane may be', 'An ellipse', 'A circle', 'A straight line', 'Any of these', 'd', ''),
(18, 'If the top view of a plane is a rhombus the object may be', 'A square', 'A rhombus', 'Either (a) or (b)', 'Neither (a) nor (b)', 'c', ''),
(18, 'The trace of a hexagonal plane may be', 'A straight line', 'A point', 'A hexagon', 'An equilateral triangle', 'd', ''),
(18, 'A 60? set-square hasitsshortest edge in the VP.The surface is perpendicular to theHP and inclined to the VP. Its front view may appear as.', 'An equilateral triangle', 'An isosceles triangle', 'An obtuse angled triangle', 'A acute angled triangle', 'b', ''),
(18, 'A 60? set-square has its shortest edge in the HP and the surface is perpendicular to the VP. Its top view may appears as.', 'An isosceles triangle', 'A right angled triangle', 'A straight line', 'Any of these', 'd', ''),
(18, 'If both the principle views of a plane object are ellipse of the same size, the side view will be', 'A horizontal line', 'A vertical line', 'An inclined line', 'An ellipse', 'b', ''),
(18, 'A hexagon is placed parallel to vertical plane which of the following projection is true?', 'Front view-line, top view- hexagon', 'Front view- hexagon, top view- line', 'Front view ?line, top view-line', 'Top view- hexagon, side view- line', 'b', ''),
(18, 'A pentagon is placed parallel to horizontal plane which of the following projection is true?', 'Front view-line, top view- pentagon', 'Front view- pentagon, top view- line', 'Front view ?line, top view-line', 'Top view- line, side view- line', 'a', ''),
(18, 'If a plane is parallel to one of the reference plane then the projection onto the other reference planes would be a line.', 'True ', 'FALSE', '________', '_______', 'a', ''),
(18, 'The minimum number of orthographic view required to represent a solid on flat surface is', '1', '2', '3', '4', 'b', ''),
(18, 'If a right angled triangle is made to revolute about one of its perpendicular sides the solid formed is ________', 'cube ', 'triangular prism ', 'cone ', 'cylinder', 'c', ''),
(18, 'When a pyramid or a cone is cut by a plane parallel to its base, thus removing the top portion, the remaining portion is called ___________', 'Cylinder', 'frustum', 'prism', 'polyhedron', 'b', ''),
(18, 'If a solid is positioned that its axis is perpendicular to one of the reference plane. Which of the following is false?', 'Axis is parallel to other reference plane', 'Base is parallel to reference plane', 'Projection on that plane gives true shape of its base', 'Base is perpendicular to horizontal plane', 'd', ''),
(18, 'When the axis of solid is perpendicular to H.P, the ______view should be drawn first and ____ view then projected from it.', 'front , top', 'top, side', 'side, front', 'top, front', 'd', ''),
(18, 'When the axis of solid is parallel to H.P &V.P, then ______view should be drawn first and ____ and _______view then projected from it.', 'front , top, side', 'top, side, front', 'side, front, top', 'top, front, side', 'c', ''),
(18, 'The front view, side view and top view of a regular square pyramid standing on horizontal plane base on horizontal plane.', 'triangle, triangle and square', 'square, triangle and triangle', 'square, triangle and square', 'triangle, square and triangle', 'a', ''),
(18, 'The side view, top view and front view of a regular pentagonal prism placed axis perpendicular to vertical plane.', 'rectangle, rectangle and pentagon', 'pentagon, rectangle and rectangle', 'pentagon, rectangle and pentagon', 'rectangle, pentagon and rectangle', 'a', ''),
(18, 'A regular pentagon prism first placed in such a way its axis is perpendicular to V.P and one edge is parallel to H.P and next this is tilted such that its axis is making some acute angle with V.P. The front view for previous and later one will be _', 'pentagon, pentagon ', 'rectangle, pentagon ', 'pentagon, irregular hexagon ', ' irregular hexagon, pentagon', 'c', ''),
(18, 'A triangular pyramid is placed such that its axis is perpendicular to V.P and one of its base?s edges is parallel to H.P the front view and top view will be _____________', 'Triangle of base, triangle due to slanting side', 'Triangle due to slanting side, triangle of base', 'Triangle of base, rhombus', 'Rhombus, triangle of base', 'a', ''),
(18, 'A cylinder first placed in such a way its axis is perpendicular to H.P and next this is tilted such that its axis is making some acute angle with H.P. The front view for previous and later one will be _________', 'circle, rectangle with circular ends', 'rectangle, rectangle', 'rectangle with circular ends, rectangle', 'circle, rectangle', 'b', ''),
(18, 'When a solid is placed such that axis is inclined with the H.P and parallel to the V.P. Its projections are drawn in __________ stages.', '1', '4', '2', '3', 'c', ''),
(18, 'While cutting, if the plane is at an angle and it cuts all the generators, then the conic formed is called as ______', 'circle', 'ellipse', 'parabola', 'hyperbola', 'b', ''),
(18, 'If the plane cuts at an angle to the axis but does not cut all the generators then what is the name of the conics formed?', 'ellipse', 'hyperbola ', 'circle ', 'parabola', 'd', ''),
(18, 'The locus of point moving in a plane such that the distance between a fixed point and a fixed straight line is constant is called as _______', 'conic', 'rectangle ', 'square ', 'polygon', 'a', ''),
(18, 'The ratio of the distance from the focus to the distance from the directrix is called as eccentricity.', 'true ', 'FALSE', '______', '______', 'a', ''),
(18, 'Which of the following has an eccentricity less than one?', 'Circle ', 'parabola', 'hyperbola', 'ellipse', 'd', ''),
(18, 'f the distance from the focus is 10 units and the distance from the directrix is 30 units, then what is the eccentricity?', '0.3333', '0.8333', '1.6667', '0.0333', 'a', ''),
(18, 'If the value of eccentricity is 12, then what is the name of the conic?', 'Ellipse', 'Hyperbola', 'Parabola', 'Circle', 'b', ''),
(18, 'If the distance from the focus is 2 mm and the distance from the directrix is 0.5 mm then what is the name of the conic section?', 'circle', 'ellipse', 'parabola', 'hyperbola ', 'd', ''),
(18, 'The cross-section gives a __________ when the cutting plane is parallel to axis of cone.', 'parabola ', 'hyperbola', 'circle ', 'ellipse', 'b', ''),
(18, 'Rectangular hyperbola is one of the hyperbola but the asymptotes are perpendicular in case of rectangular hyperbola.', 'TRUE', 'FALSE', '______', '______', 'a', ''),
(18, 'The angle between the isometric axes is __________', '180 degrees', '60 degrees', '90 degrees', '120 degrees', 'd', ''),
(18, 'he value of the ratio of isometric length to true length is _______', '0.141', '0.372', '0.815', '0.642', 'c', ''),
(18, 'The lines parallel to isometric axes are called ________ lines.', 'parallel', 'auxiliary', 'isometric', 'oblique', 'c', ''),
(18, 'Isometric view of cube is drawn the angle between the edge of cube and horizontal will be______', '15 degrees ', '120 degrees', '45 degrees', '30 degrees', 'd', ''),
(18, 'The objects we see in nature will be in Isometric view', 'true ', 'FALSE', '______', '______', 'b', ''),
(18, 'Isometric view of cube is drawn and faces of cube are seen as ______', 'square', 'rectangle', 'rhombus', 'parallelogram', 'c', ''),
(18, 'If an isometric projection is drawn with true measurements but not with isometric scale then the drawings are called ____________', 'Isometric projection', 'Isometric view', 'Isometric perception', 'Orthographic view', 'b', ''),
(18, 'Isometric view of equilateral triangle will be ____________', 'equilateral triangle', 'scalene triangle', 'isosceles triangle', 'right angled triangle', 'b', ''),
(18, 'Front view of circle is given and isometric view is to be drawn which of the following is correct procedure in drawing isometric view?', 'turning the circle such that line on diameter is making 30 degrees with horizontal', 'by increasing or decreasing angles between two perpendicular line on diameter at required proportions', 'drawing line in diameter parallel to isometric axes', 'enclosing circle in a square and aligning square to isometric axes and pointing four points on circle touching the square and joining by smooth curve.', 'd', ''),
(18, 'The following method(s) is used to find the true length and true inclination of a line when its front view and top view are given', 'Rotation method', 'Trapezoidal method', 'Auxiliary plane method', 'All of the above', 'd', ''),
(18, 'The front view of a rectangle, when its plane is parallel to HP and perpendicular to VP, is', 'rectangle', 'square', 'line', 'point', 'c', ''),
(18, 'Which of the following position is not possible for a plane?', 'Perpendicular to both HP and VP', 'Parallel to both HP and VP', 'Perpendicular to HP and parallel to VP', 'Perpendicular to VP and parallel to HP', 'b', ''),
(18, 'The following are the Polyhedron except', 'prism', 'pyramid ', 'cube', 'cylinder ', 'd', ''),
(18, 'The following are the Solids of revolution except', 'prism', 'sphere', 'cone', 'cylinder ', 'a', ''),
(18, 'If a solid is cut by a cutting plane parallel to the base of the solid and top part is removed, the remaining part is called', 'Frustum of a solid', 'Truncated solid', 'Oblique solid', 'None of the above', 'a', ''),
(18, 'A right regular hexagonal prism in resting on HP on its base, its top view is a', 'square', 'rectangle', 'hexagon', 'pentagon', 'c', ''),
(18, 'Which of the following position is not possible for a right solid?', 'Axis perpendicular to HP and parallel to VP', 'Axis parallel to VP and perpendicular to HP', 'Axis parallel to both VP and HP', 'Axis perpendicular to both VP and HP', 'd', ''),
(18, 'The top view of a right cylinder resting on HP on its base rim is', 'ellipse', 'circle', 'rectangle', 'square', 'b', ''),
(18, 'A tetrahedron has four equal ____ faces', 'square', 'rectangular', 'triangular', 'None of the above', 'c', ''),
(18, 'The following is formed by revolving rectangle about one of its sides which remains fixe', 'cylinder', 'sphere', 'hemi sphere', 'cone', 'a', ''),
(18, 'The sectional plane are represented by', 'Continuous thick line', 'Continuous thin line', 'Chain thin line', 'Chain thin line having thick edges', 'd', ''),
(18, 'A right circular cone resting on HP on its base is cut by a section plane parallel to HP, bisecting its axis. The true shape of the section is', 'parabola', 'hyperbola', 'ellipse', 'circle', 'd', ''),
(18, 'A right circular cylinder resting on HP on its base is cut by a section plane inclined to HP, bisecting its axis. The true shape of the section is', 'parabola', 'hyperbola', 'ellipse', 'circle', 'c', ''),
(18, 'The following is the method for development of a right regular prism', 'Parallel line method', 'Radial line method', 'Triangulation method', 'Approximate method', 'a', ''),
(18, 'The following is the method for development of a sphere.', 'Parallel line method', 'Radial line method', 'Triangulation method', 'Approximate method', 'd', ''),
(18, 'Development of surfaces is used in the development of', 'Piping', 'Air conditioning duct', 'Buckets', 'All of the above', 'd', ''),
(18, 'The development of cylinder is a', 'rectangle', 'circle', 'ellipse', 'None of the above', 'a', ''),
(18, 'Zone method is used to develop', 'prism', 'pyramid ', 'cone', 'sphere', 'd', ''),
(18, 'The development of lateral surfaces of a pentagonal pyramid is', 'five squares', 'five rectangles ', 'five triangles ', 'None of the above', 'c', ''),
(18, 'The isometric length is ____ percent of actual length', '0:00:00', '71.5', '81.5', '91.5', 'c', ''),
(18, 'The following is (are) the method(s) of projecting the pictorial views.', 'Axonometric projection', 'Oblique projection', 'Perspective projection', 'All of the above', 'd', ''),
(18, 'The isometric axis are inclined at ___ degree to each other', '60', '90', '120', '150', 'c', ''),
(18, 'The following are the methods for drawing isometric views except', 'Box method', 'Offset method', 'Centre lines method', 'Parallel line method', 'd', ''),
(18, 'Rectagular prism is an example of', 'Objects having isometric lines', 'Object having non-isometric lines', 'Object having curved surfaces', 'None of the above', 'a', ''),
(18, 'The isometric projection of a sphere is a', 'Circle', 'Ellipse', 'Hyperbola', 'Parabola', 'a', ''),
(18, 'The isometric projection of a circle is a', 'Circle', 'Ellipse', 'Hyperbola', 'Parabola', 'b', ''),
(18, 'When creating an isometric drawing in Auto-CAD the drafter can utilize the Dynamic Input and Polar Coordinate system to place both vertical and horizontal lines. A line created from one point 3 inches at 180 degrees would be a ________ line.', 'Horizontal', 'Vertical', 'Inclined', 'None of the above', 'b', ''),
(18, 'The type of line that projects from an object for the express purpose of locating a dimension is a ________ line.', 'Visible', 'Hidden', 'Extension', 'Dimension', 'c', ''),
(18, 'This is the measured size of a finished part:', 'Actual size', 'Dimensioned size', 'Production size', 'Basic size', 'a', ''),
(18, 'Drafters should use a ________ in a section view of a mechanical part that includes the cylindrical view of a threaded hole.', 'Center line', 'Hatch line', 'Poly line', 'Dimension line', 'a', ''),
(18, 'A ________ section allows the drafter to create a Cutting Plane line which is not in a straight line across the part.', 'Offset', 'Half', 'Whole', 'Broken out', 'a', ''),
(18, 'Lines of an isometric drawing that are not parallel to the isometric axes are called this:', 'Trimetric lines', 'Non-isometric lines', 'Multiview lines', 'Dimetric lines', 'b', ''),
(18, 'This type of section is limited by a break line:', 'Removed section', 'Revolved section', 'Broken-out section', 'Half section', 'c', ''),
(18, 'Isometric drawings are often used by ________ to help illustrate complex designs.', 'Mechanical engineers', 'Piping drafters', 'Aerospace engineers', 'All of the above', 'd', ''),
(18, 'When creating a Cutting Plane line with Auto-CAD it is customary to use a ________ to create the line.', 'Center line', 'Polyline', 'Dashed line', 'Hatch lin', 'b', ''),
(18, 'How can the drafter prevent Auto-CAD from placing or stacking another center mark on a circle when adding a diameter dimension to it?', 'Explode the dimension and then erase the center mark', 'Use the Properties dialog box to turn off the center mark of the dimension', 'It cant be done', 'Use the trim tool to take away the stacked center mark', 'b', ''),
(18, 'If designs require changes, they should be documented with:', 'Development plans', 'Product proposals', 'Document reviews', 'Engineering change orders', 'd', ''),
(18, 'Some of the common terms used to describe technical drawing include:', 'Drafting', 'Engineering Graphics', 'Engineering Drawing', 'All of the abov', 'd', ''),
(18, 'In U.S. structural and architectural drafting, all dimensions of this length are usually expressed in feet and inches:', 'One inch or over', 'One foot or over', 'One yard or ove', 'One rod or over', 'b', ''),
(18, 'This type of structural steel drawing shows all dimensions necessary for fabrication:', 'Shop drawings', 'Design drawings', 'Weldment drawings', 'Application drawings', 'a', ''),
(18, 'These maps are used in planning installations of trees, shrubbery, drives, and other garden features:', 'Landscape maps', 'Engineering maps', 'Topographic maps', 'Cadastral maps', 'a', ''),
(18, 'It is customary for the first sheet of a working drawing set to include __________.', 'A parts list', 'Exploded assembly', 'Assembled assembly', 'All of the above', 'd', ''),
(18, 'Some common blocks used by architectural drafters include __________.', 'Door swings', 'Ceiling fans', 'Appliances', 'All of the abov', 'd', ''),
(18, 'The second line of dimensions out from the plan generally includes _________', 'Centers of doors and windows', 'The distances between outside walls and interior walls', 'The measurement from the outside of the brick to the inside of the exterior wall', 'The measurement from one outside corner to the opposite outside corner', 'b', ''),
(18, 'Some of the standard Auto-CAD text styles used in architectural drawings includes _________.', 'City Blueprint', 'Country Blueprin', 'Stylus BT', 'All of the abov', 'd', ''),
(18, 'A fillet is a rounded surface on the ________ corner of a part.', 'Inside', 'Outside', 'radial', 'Isoplane', 'a', ''),
(18, 'A round is a rounded surface on the ________ corner of a part.', 'Inside', 'Outside', 'radial', 'Isoplane', 'b', ''),
(18, 'Using this as a communication and design review tool can help shorten the process and eliminate productivity barriers', 'Development plans', 'Portable document files', 'The Internet and e-mail', 'Gantt charts', 'c', ''),
(18, 'A full scale technical drawing will have a scale factor of', '1:01', '1:02', '2:01', '1:04', 'a', ''),
(18, 'When using the direct entry method to create a horizontal line exactly three inches long the drafter should ________ first.', 'Pull the line from away from the starting point very carefully', 'Insure that Ortho is on', 'Enter 3 for the length of the line', 'Read the coordinate position on the Dynamic Readout', 'b', ''),
(18, 'This is a flat or rounded tab protruding from a surface, usually to provide a method for attachment:', 'Lug', 'Boss', 'Chamfer', 'Spot face', 'a', ''),
(18, 'The condition of a part when it contains the least amount of material is referred to as ________.', 'Smallest', 'lmc', 'mmc', 'actual size', 'b', ''),
(18, 'The typical parts list should include the _________.', 'Part number', 'Manufacturing material', 'Number of parts needed', 'All of the above', 'd', ''),
(18, 'The title block used on working drawings should include the', 'Sheet number', 'Line type', 'Layer set', 'All of the above', 'a', ''),
(18, 'The thread note for a typical bolt will include the _________.', 'Major diameter of the thread', 'Material', 'Center line', 'Offset distance', 'a', ''),
(18, 'Several of the tools used in traditional drafting include the following:', 'Parallel straight edge', '45 degree triangle', 'Circle template', 'All of the above', 'd', ''),
(18, 'This type of drawing shows two lines representing the pipe diameter:', 'Single-line', 'Double-line', 'Standard piping', 'Centerline piping', 'b', ''),
(18, 'A circular arc is dimensioned in the view where you see its true shape by giving the value for its:', 'Diameter', 'Arc length', 'Radius', 'Chord length', 'c', ''),
(18, 'In oblique projection, important shapes should be in this position relative to the viewing plane:', 'Parallel', 'Perpendicular', 'Adjacent', 'Rotated', 'a', ''),
(18, 'This should show what changes were made, when, and by whom:', 'Portable document', 'Record of revisions', 'Title form', 'Revision drawings', 'b', ''),
(18, 'This is how axonometric, oblique, and perspective sketches show objects:', 'Orthographically', 'Pictorially', 'Obliquely', 'Parallel', 'b', ''),
(18, 'The foundation contractor will work with the following architectural plans.', 'Foundation', 'Site plan', 'Floor plan', 'All of the above', 'd', ''),
(18, 'In this type of drawing, vertical pipes may be revolved into the horizontal plane:', 'Standard view', 'Elevation view', 'Transverse piping', 'Developed piping', 'd', ''),
(18, 'A half-moon protractor is divided into how many degrees?', '360', '180', '270', '310', 'b', ''),
(18, 'In an assembly section, these parts should have their section lines left out or shown solid black:', 'Bolts', 'All fasteners', 'Thin parts', 'Rivets', 'c', ''),
(18, 'This type of rapid prototyping system uses a laser to fuse powdered metals, plastics, or ceramics:', 'Fused deposition modeling', 'Stereo lithography apparatus', 'Solid ground curing', 'Selective laser sintering', 'd', ''),
(18, 'In developing a multi-view drawing, the drafter can use a ________ line to help locate the top and right side views.', 'Object', 'Hidden', 'Dimension', 'Miter', 'd', ''),
(18, 'This material is used in masonry construction, most commonly for ornamental facing:', 'Face brick', 'Clay tile', 'Natural stone', 'Aggregate', 'c', ''),
(18, 'CAD programs which incorporate parametric modeling utilize a system in which the dimensions control the ________.', 'Size and shape of the model features', 'Perspective of the model', 'Shading used to render the model', 'All of the above', 'a', ''),
(18, 'The most common geometric form used in gears today is this:', 'Involute profile', 'Convolute profile', 'Base circle', 'Spur circle', 'a', ''),
(18, 'In an exploded assembly drawing it is customary for the drafter to use a ________ line to illustrate how parts fit together.', 'Phantom', 'Hidden', 'Dashed', 'Center', 'a', ''),
(18, 'This type of drawing is created to calculate areas, locate property lines, and locate building projects and facilities:', 'Traverse', 'Contour', 'City map', 'Plat', 'd', ''),
(18, 'Architectural drafters generally prefer to use ________ drawings to help illustrate 3-dimensional views of a structure.', 'Isometric', 'Perspective', 'Orthographic', 'Auxiliary', 'b', ''),
(18, 'When creating a block the drafter needs to pay particular attention to selecting a base point because it determines the', 'Scale', 'Rotation angle', 'Insertion poin', 'Color', 'c', ''),
(18, 'This is used to indicate that a surface is to be machined:', 'Finish mark', 'Machining mark', 'Roughness indicator', 'Coordinate mark', 'a', ''),
(18, 'This allows the designer to conceptualize objects more easily without having to make costly illustrations, models, or prototypes:', 'Computer-aided manufacturing', 'Computer-aided design', 'Computer-aided engineering', 'Computer-aided prototyping', 'b', ''),
(18, 'Which tool can be used to draw a 90 degree angle?', '30/60 triangle', 'Protractor', 'Drafting machine', 'All of the above', 'd', ''),
(18, 'Which set of lead grades has a grade out of sequence?', 'H, HB, B, 3B', '7B, H, F, 3H', '6B, B, H, 4H', '9H, HB, B, 2B', 'b', ''),
(18, 'Which type of line is part of a dimension?', 'Break lines', 'Phantom lines', 'Extension lines', 'Cutting plane lines', 'c', ''),
(18, 'Which type of line is particular to section drawings?', 'Break lines', 'Phantom lines', 'Extension lines', 'Cutting plane lines', 'd', ''),
(18, 'Which angle cannot be made with either a 45 or 30/60 triangle or a combination of the two?', '90', '70', '30', '15', 'b', ''),
(18, 'A drawing instrument set usually contains all of the following, except:', 'Bow compass', 'scale', 'dividers', 'Extra leads', 'd', ''),
(18, 'Which line type is thin and light?', 'Visible lines', 'Center lines', 'Construction lines', 'all of the above', 'c', ''),
(18, 'Which line type is thick and black?', 'Visible lines', 'Center lines', 'Construction lines', 'all of the above', 'a', ''),
(18, 'Which type of line has precedence over all other types of lines?', 'A hidden line', 'A center line', 'A visible line', 'None of the above', 'c', ''),
(18, 'Which statement(s) is true about the precedence of lines?', 'A hidden line has precedence over a center line', 'A center line has precedence over a visible line', 'A visible line has precedence over a miter line', 'All of the above', 'a', ''),
(18, 'When you want to make the letters of a line of text narrower, you would set its:', 'Aspect', 'Scale', 'Alignment', 'Font', 'a', ''),
(18, 'When you want to make sure that all of the text stays to the right of a given point on the', 'Aspect', 'Scale', 'Alignment', 'Font', 'c', ''),
(18, 'The primary unit of measurement for engineering drawings and design in the mechanical industries is the', 'Millimeter', 'Centimeter', 'Meter', 'Kilometer', 'a', ''),
(18, 'To draw the leader line, which type of the following line is used?', 'Continuous thick line', 'Long chain thin line', 'Continuous thin wavy line', 'Continuous line', 'a', ''),
(18, 'A French curve is used to draw', 'Circle', 'Ellipse', 'Smooth free form curve', 'Polygon', 'c', '');
