

INSERT INTO `mcq` (`mcq_cat_id`, `mcq`, `op1`, `op2`, `op3`, `op4`, `cop`, `desc`) VALUES
(0, 'mcq', 'op1', 'op2', 'op3', 'op4', 'cop', 'desc'),
(10, 'Context free grammar is___________.', 'Compiler', 'language expression', 'language translator', 'none of these', 'b', 'Not Available'),
(10, 'Which of the following does not belong to context free grammer?', 'non terminal symbol', 'terminal symbol', 'start symbol', 'end symbol', 'd', 'Not Available'),
(10, 'Regular grammer is', 'context free grammer', 'non context free grammer', 'simple english grammer', 'none of these', 'a', 'Not Available'),
(10, 'S_> aSa[bSb][a]b;The language generated by the above grammer over the alphabet {a,b}is the set of_________.', 'all palindromes', 'all odd length palindromes', 'strings with same symbol', 'all even length palindroms', 'd', 'Not Available'),
(10, 'The CFG S--> aS|bS\\a\\b is equivalent to regular expression___________.', '(a+b)', '(a+b)(a+b)*', '(a+b)(a+b)', 'none of these', 'b', 'Not Available'),
(10, 'Context free grammer is closed under___________.', 'union', 'kleen star', 'concatenation', 'all of them', 'd', 'Not Available'),
(10, 'The language {} is___________.', 'regular', 'context free but non regular', 'context sensitive but not free', 'none of these', 'b', 'Not Available'),
(10, 'A grammer is____________device.', 'generative', 'congnitive', 'acceptor', 'can\'t say', 'a', 'Not Available'),
(10, 'The context free grammer S SS|0S1|1S0| generates____________.', 'equal number of 0\'s and 1\'s', 'unequal number of 0\'sand 1\'s', 'any number of 0\'s followed by any number of1\'s', 'none of these', 'a', 'Not Available'),
(10, 'The Chomsky normal form is____________.', 'nonterminal->nonterminal nonterminal', 'nonterminal ->terminal nonterminal', 'nonterminal->nonterminal', 'none of these', 'a', 'Not Available'),
(10, 'The Chomsky normal form is____________.', 'nonterminal->nonterminal nonterminal', 'nonterminal ->terminal nonterminal', 'nonterminal->nonterminal', 'none of these', 'b', 'Not Available'),
(10, 'Give a grammer in GNF and a derived string in the grammer with the length n,any______will halt at depth n.', 'top-down parser', 'bottom-up parser', 'multitape turing machine', 'none of the mentioned', 'a', 'Not Available'),
(10, 'In order to simplify a context free grammer ,we can skip the following operations:', 'removal of null production', 'removal of useless symbols', 'removal of unit productions', 'none of the mentioned', 'd', 'Not Available'),
(10, 'Which among the following is a unit production .', 'A->BB', 'A->B', 'A->BC', 'all of tha above', 'b', 'Not Available');

